import type { Metadata } from "next";
import "./globals.css";
import React from "react";

import Header from "@front/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ko">
      <body className="antialiased bg-stone-50 dark:bg-stone-700">
        <Header />
        {children}
      </body>
    </html>
  );
};


export default RootLayout;